spring:
  application:
    name: sportsdb-collector
    index: 0

okhttp3:
  readTimeout: '{cipher}AQCJExeXGCr9mtM02O/KEUhWx00Y9Ky449X8GoWgsmNcxTX22AFi4o/FGFkjNz0WteB8Sp+PVdyncmJplO4BaSoP20dz063tIYRFUmft4fQNoOf5GoJTeTptpBcZ1SguoicyXi7oy7sjdK5JZwA86V5MDO2vrHAgFvm4sqAnZ0iYvWw/zobpq8a4U9ls/H4c2KmpXtIw23+0LHuiAAj2eVhMyBG3D+W5hvMqC+i44nFKmj1VP9BGVRvx5mrnQeWWsQrM2M81EW2OcrB6wNFnqXhUs1NM17MSZlelgPxiLWoHLvMcrpzSk4BmRVqsRGurpQ15Eu0mBdVvRsZHPMVza7bMQ3JhMYkIr9f6OCy7Gr/L4lCy+V3lhi65mHe8h2ioC0c='
  connectTimeout: 20
  maxIdleConnections: 1
  keepAliveDuration: 1